version: "3.2"

volumes:
  mongodb_data_volume:
    external: true

services:
  mongo:
        image: tutum/mongodb:latest
        deploy:
          replicas: 1
          mode: replicated
          resources:
            limits:
              cpus: "0.5"
        ports:
          - "27017:27017"
        environment:
            MONGODB_USER: "admin"
            MONGODB_PASS: "123456"
            MONGODB_DATABASE: "clb"
        volumes:
          - type: volume
            source: mongodb_data_volume
            target: /data/db
  ftp:
     image: stilliard/pure-ftpd:latest
     deploy:
       replicas: 1
       mode: replicated
       resources:
         limits:
           cpus: "0.3"
     ports:
       - "22:22"
networks:
  overlay:


