version: "3.2"

volumes:
  mongodb_data_volume:
    external: true

services:
  mongo:
        image: tutum/mongodb:latest
        deploy:
          replicas: 1
          mode: replicated
          resources:
            limits:
              cpus: "0.5"
        ports:
          - "27017:27017"
        environment:
            MONGODB_USER: "admin"
            MONGODB_PASS: "123456"
            MONGODB_DATABASE: "clb"
        volumes:
          - type: volume
            source: mongodb_data_volume
            target: /data/db
  ftp:
     image: stilliard/pure-ftpd:hardened
     deploy:
       replicas: 1
       mode: replicated
       resources:
         limits:
           cpus: "0.3"
     ports:
        - "21:21"
        - "30000-30009:30000-30009"
     
     #volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
     #   - "/c/Users/nobre/CLB/empty:/home/username/"
     #   - "/c/Users/nobre/CLB/empty/passwd:/etc/pure-ftpd/passwd"
     environment:
         PUBLICHOST: 192.168.99.100
         FTP_USER_NAME: bob
         FTP_USER_PASS: bob
         FTP_USER_HOME: /home/bob
networks:
  overlay:


