apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clbapp-project
spec:
  replicas: 1
  template:
   metadata:
    labels:
     app: clbapp
     department: energy
   spec:
    containers:
    - name: clbapp
      image: clbproject/clbapp
      ports:
      - name: clbapp-port
        containerPort: 8080
    - name: mongod-container
      image: mongo
      ports:
      - name: mongodb-port
        containerPort: 27017
      env:
       - name: MONGO_USER
         value: "admin"
       - name: MONGO_PASSWORD
         value: "123456"
       - name: MONGO_DATABASE
      volumeMounts:
      - name: mongodb-volume
        readOnly: true
        mountPath: /etc/secrets-volume
    volumes:
    - name: mongodb-volume